### ISSUE TITLE
Arabada cam kapalı iken telefon bugu.

### ISSUE THREAD

**Issue by Faxonn0** [inceptionnet/wiki#3]
Türkiye Roleplay.

Arabada cam kapalıyken yazılanları dışarda rol yapanların görme bugu düzeltilmeli artık, çok sinir bozucu oluyor bazı durumlarda.

@QueryOfficial @cleoppa

**Comment by cleoppa** [comment]
Geri zekalı olabilir misin ki wiki repositorysinde alakasız issue açıyorsun
